#ifndef RACHELWTZ__STREAMS__HPP
#define RACHELWTZ__STREAMS__HPP

#include "rw-strings.hpp"

#define RACHELWTZ_STREAMS_NAMESPACE streams
#define RACHELWTZ_STREAMS_BEGIN     namespace RACHELWTZ_NAMESPACE::RACHELWTZ_STREAMS_NAMESPACE {
#define RACHELWTZ_STREAMS_END       }
#define USING_RACHELWTZ_STREAMS     using namespace ::RACHELWTZ_NAMESPACE::RACHELWTZ_STREAMS_NAMESPACE

RACHELWTZ_STREAMS_BEGIN



RACHELWTZ_STREAMS_END
#endif